/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.vincentfree.app

import com.github.vincentfree.verticles.RestVerticle
import io.vertx.config.ConfigRetriever
import io.vertx.core.Vertx
import io.vertx.kotlin.core.deploymentOptionsOf
import io.vertx.kotlin.core.vertxOptionsOf
import io.vertx.kotlin.coroutines.await
import io.vertx.tracing.opentracing.OpenTracingOptions
import kotlinx.coroutines.runBlocking
import org.apache.logging.log4j.LogManager
import kotlin.system.exitProcess

private val logger = LogManager.getLogger("AppKt")
fun main() = runBlocking<Unit> {
    System.setProperty("JAEGER_SERVICE_NAME","appService")

    val vertxOptions = vertxOptionsOf(
        tracingOptions = OpenTracingOptions()
    )
    val vertx = Vertx.vertx(vertxOptions)
    val configRetriever = ConfigRetriever.create(vertx)
    val config = configRetriever.config.await()
    val appId = kotlin.runCatching {
        vertx.deployVerticle(RestVerticle(), deploymentOptionsOf(config = config)).await()
    }.getOrElse {
        logger.error("failed to start the application due to this error: ${it.message}")
        exitProcess(1)
    }
    logger.info("Application started, ID:$appId")
}
